sharkpitch/accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import *


urlpatterns=[
    path('profile/', views.profile_view, name='profile_view'),
    path('login/',views.login_view,name='login_view'),
    path('Investor_landing/',views.Investor_landing,name='Investor_landing'),
    path('startup/<int:user_id>/', views.startup_home_view, name='startup_home'),
    path('startup_landing/', views.startup_landing, name='startup_landing'),
    path('verification1/',views.startup_register1_view,name='startup_register1_view'),
    path('verification2/',views.startup_register2_view,name='startup_register2_view'),
    path('verification3/',views.startup_register3_view,name='startup_register3_view'),
    path('verification4/',views.startup_register4_view,name='startup_register4_view'),
    path('verification5/',views.startup_register5_view,name='startup_register5_view'),
    path('verification6/',views.startup_register6_view,name='startup_register6_view'),
    path('verification7/',views.startup_register7_view,name='startup_register7_view'),
    path('verification8/',views.startup_register8_view,name='startup_register8_view'),
    path('verification9/',views.startup_register9_view,name='startup_register9_view'),
    path('verification10/',views.startup_register10_view,name='startup_register10_view'),
    path('signup/',views.signup_view,name='signup_view'),
    path('logout/', views.logout, name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_name='accounts'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sharkpitch/mainapp/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views 
urlpatterns = [
    path('',views.home,name='home'),
    path('investor_landing',views.Investor_landing,name='Investor_landing'),
    path('Investor_profile',views.Investor_profile,name='Investor_profile'),
    path('user_profile',views.User_profile,name='User_profile'),
    path('login',views.login,name='login'),
    path('signup',views.signup,name='signup'),
    path('verification1',views.verification1,name='verification1'),
    path('verification2',views.verification2,name='verification2'),
    path('verification3',views.verification3,name='verification3'),
    path('verification4',views.verification4,name='verification4'),
    path('verification5',views.verification5,name='verification5'),
    path('verification6',views.verification6,name='verification6'),
    path('verification7',views.verification7,name='verification7'),
    path('verification8/',views.verification8,name='verification8'),
    path('verification9',views.verification9,name='verification9'),
    path('verification10',views.verification10,name='verification10'),
    path('investor_description',views.investor_description,name='investor_description'),
    path('interested',views.interested,name='interested'),
    path('startup_info',views.startup_info,name='startup_info'),
    path('startup_home',views.startup_home,name='startup_home'),
    path('mainapp/interested_page', views.index, name='Interested_page'),  # Page with the button
]

sharkpitch/sharkpitch/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("mainapp.urls")),
    path('accounts/',include("accounts.urls")),
]

sharkpitch/templates/Interested_page.html
{% load static %}
{% include 'header.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Communication Options</title>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
  <style>
/* General Styles */
html, body {
  height: 100%;
  margin: 0;
  padding: 0;
}

body {
  font-family: 'Roboto', sans-serif;
  background-color: #ffffff;
  display: flex;
  flex-direction: column;
}

.page-wrapper {
  flex: 1 0 auto;
  display: flex;
  flex-direction: column;
}

.container {
  max-width: 1200px;
  width: 100%;
  margin: 0 auto;
  padding: 20px;
  flex: 1 0 auto;
  display: flex;
  justify-content: center;
  align-items: center;
}

/* Options Container */
.options-container {
  display: flex;
  justify-content: center;
  align-items: flex-start;
  gap: 40px;
}

.option {
  display: flex;
  flex-direction: column;
  align-items: center;
  width: 300px;
}

.option-image {
  width: 250px;
  height: 250px;
  object-fit: cover;
  margin-bottom: 20px;
}

/* Button Styles */
.option-button {
  background-color: #114E71;
  color: white;
  border: none;
  padding: 10px 20px;
  font-size: 1rem;
  border-radius: 5px;
  cursor: pointer;
  transition: background-color 0.3s ease;
  width: 100%;
  text-align: center;
}

.option-button:hover {
  background-color: #0d3b54;
}

/* Footer Styles */
.footer {
  flex-shrink: 0;
  text-align: center;
  color: #666;
  font-size: 0.875rem;
  padding: 20px 0;
  background-color: #f8f8f8;
  width: 100%;
}

/* Media Queries */
@media (max-width: 768px) {
  .options-container {
      flex-direction: column;
      align-items: center;
      gap: 20px;
  }

  .option {
      width: 100%;
      max-width: 300px;
  }

  .option-button {
      font-size: 0.9rem;
  }
}

@media (max-width: 480px) {
  .option-image {
      width: 200px;
      height: 200px;
  }

  .option-button {
      font-size: 0.8rem;
      padding: 8px 15px;
  }
}
  </style>
</head>

<body>
  <div class="page-wrapper">
    <!-- Main Content Section -->
    <main class="container">
      <div class="options-container">
        <div class="option">
          <img src="{% static 'images/videocall_img.png' %}" alt="Video call illustration" class="option-image">
          <a href="http://127.0.0.1:8001/" target="_blank" class="btn btn-primary"><button class="option-button">Real-time video conferencing</button></a>
        </div>
        <div class="option">
          <img src="{% static 'images/chat_img.png' %}" alt="Chat illustration" class="option-image">
          <a href="http://127.0.0.1:8002/" target="_blank" class="btn btn-primary"><button class="option-button">Communicate via chat</button></a>
        </div>
      </div>
    </main>
    <p style="text-align:center">The Room name is same as Company Name <span style="color: gray;">(without spaces)</span></p>

    <footer class="footer">
      &copy; 2024 Shark Pitch. All rights reserved.
    </footer>
  </div>
</body>

</html>
{% endblock %}

sharkpitch/templates/Investor_landing.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>investor landing</title>
    <link rel="stylesheet" href="{% static 'styles/css/Investor_landing.css' %}">
    <style>
        body{
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        }
    </style>
</head>
<body>  
    <header>
        <img src="{% static 'styles/images/shark_pitch_logo.jpg' %}" alt="" id="logo">
       <a href="{% url 'home' %}" id="shark">SHARK PITCH</a>
       <div id="sb">
        <label class="input input-bordered flex items-center gap-2" id="sb" >
            <svg
            id="sicon"  
            viewBox="0 0 16 16"
            fill="currentColor"
            class="h-4 w-4 opacity-70">
            <path
                fill-rule="evenodd"
                d="M9.965 11.026a5 5 0 1 1 1.06-1.06l2.755 2.754a.75.75 0 1 1-1.06 1.06l-2.755-2.754ZM10.5 7a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0Z"
                clip-rule="evenodd" />
            </svg>
            <input type="text" placeholder="Search" id="search-bar"/>
        </label>          
    </div>
        <a href="{% url 'home' %}" id="about">About Us</a>
        <a href="{% url 'home' %}" id="contact">Contact Us</a>
        <a href="{% url 'accounts:logout' %}" id="logout">Logout</a>
        <a href="{% url 'accounts:profile_view' %}"><img src="{% static 'styles/images/profile.jpg' %}" alt="" id="prof"></a>
    </header>
    <div id="domains">
        <h2 id="dom">DOMAINS :</h2>
        <ul id="unl">
        <li class="category" data-category="food">FOOD</li>
        <li class="category" data-category="life style">LIFE STYLE</li>
        <li class="category" data-category="education">EDUCATION</li>
        <li class="category" data-category="finance">FINANCE</li>
        <li class="category" data-category="health">HEALTH</li>
        <li class="category" data-category="others">OTHERS</li>
        <li class="category" data-category="all">SHOW ALL</li>
        </ul>
    </div>
    <div id="h3">
        
        <div id="dd">
            <details class="dropdown" id="dd1">
                <summary class="btn m-1" id="filter">Filter by</summary>
                <div id="dropdown-content">
                    <ul class="menu dropdown-content bg-base-100 rounded-box z-[1] w-52 p-2 shadow" id="dd1">
                    <li>Lastest</li>
                    <li>Oldest</li>
                    <li>Service</li>
                    <li>Product</li>
                    <li>Growth</li>
                    <li>Value</li>
                    </ul>
                </div>
              </details>
        </div>
    </div>
    
    <br id="br">
    <div>
    <div class="video-container">
    {% if video_data %}
        {% for video in video_data %}
            <div class="video-item" id="clickable-video" data-tag="{{ video.tag }}">
                <video id="uploadedVideo" src="..{{ video.video_url}}" controls></video>
                <h2 id="us" style="cursor:pointer;" class="video-name" onclick="window.location.href='{% url 'accounts:startup_home' user_id=video.user_id %}'">
                    {{ video.Company_Name }}'s pitch
                </h2>
                <p id="us" style="cursor:pointer;">by {{ video.Founder_Name }}, a founder and CEO</p>
            </div>
        {% endfor %}
    {% else %}
        <p>No videos available.</p>
    {% endif %}
    </div>
    <script src="{% static 'styles/js/Investor_landing.js' %}"></script>
</body>
</html>

sharkpitch/templates/Startup_home.html
{% load static %}
{% include 'header.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Startup Info</title>
    <link rel="stylesheet" href="{% static 'startupstyle.css' %}">
    <link rel="stylesheet" href="{% static 'header.css' %}">
        <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">

<script type="text/javascript">
  // Load Google Charts library and the necessary packages
  google.charts.load('current', {'packages':['corechart']});
  google.charts.setOnLoadCallback(drawCharts);

  // Function to draw both charts
  function drawCharts() {
      drawPieChart();
      drawColumnChart();
  }

  // Function to draw the Pie Chart
  function drawPieChart() {
      var data = google.visualization.arrayToDataTable([
          ['Financial Term', 'Percentage'],
          ['Revenue', 50],
          ['Expenses', 30],
          ['profit', 15],
          ['Debt', 15],
         
      ]);

      var options = {
          title: 'Financial Breakdown',
          is3D: true,
      };

      var chart = new google.visualization.PieChart(document.getElementById('piechart'));
      chart.draw(data, options);
  }

  // Function to draw the Column Chart
  function drawColumnChart() {
      var data = google.visualization.arrayToDataTable([
          ['Month', 'Revenue Growth(%)','customer Growth (%)','profit Growth (%)' ],
          ['January', 10, 5,7],
          ['February', 15, 8,9],
          ['March', 20, 12,11],
          ['April', 25,15, 14]
      ]);

      var options = {
          title: 'Monthly Growth Matrix',
          chartArea: {width: '50%'},
          hAxis: {
              title: 'Month',
          },
          vAxis: {
              title: 'Growth Percentage(%)',
            
          },
          bars: 'vertical',
          colors: ['#1b9e77', '#d95f02']
      };

      var chart = new google.visualization.ColumnChart(document.getElementById('barchart'));
      chart.draw(data, options);
  }
</script> 
</head>
<body>
  
 
<p class="startup-name">{{details.Company_Name}}</p>
<p class="profile">We as <strong>"{{details.Company_Name}}"</strong></p>
<div style="display: flex; flex-direction:column;">
 
  <div class="startupinfo-profile">
    
    <div style="display:flex;">
      
        <p class="about"> <strong> Founder</strong>,<strong>{{details.Founder_Name}}</strong>: {{details.q1}}</p>
    </div> 
    <div style="width:400px;" ><img  class="profile-pic"  src="{% static 'images\founders.jpg' %}" ></div>
    <!--sharkpitch\static\images\founders.jpg-->
  </div>
  <div>
      <div>
      <p class="About">About</p>
      <p class="info">{{details.q2}}{{details.q3}} <br>{{details.q4}}{{details.q5}}</p>
      <p class="info"> <strong>Feel free to Contact us:</strong> {{details.mail}}</p>
      </div>
      <div>
      <!--<video class ="videoplayer" width="500" height="300" src="{{ details.Video_URL|slice:':/media/' }}" controls>
          <source src="..{{details.video_url}}" type="video/mp4">
              </video> -->
      </div>
      </div>
     
      
        
          <div class="chart-container">
            <!-- Pie chart -->
            <div id="piechart" class="chart"></div>
            <!-- Column chart -->
            <div id="barchart" class="chart"></div>
        </div>
      
        
         
         <div class="button" >
        <button class="intersted-button" onclick="window.location.href='{% url 'interested' %}'" style="height: 50px; width:200px; border-radius:20px; font-size:23px; cursor:pointer">Connect</button>
      </div>

</div>

     </body>
</html>
{% endblock content %}


  
    
    
   

sharkpitch/templates/User_profile.html
{% load static %}
{% include 'header.html' %}
    {% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User_profile</title>
    <link rel="stylesheet" href="{% static 'styles/css/User_profile.css' %}">
</head>
<body>
    <h1 id="myprofile">My Profile</h1>
    <div id="Main-profile-container">
        <div id="avatar-card">
            <img src="{% static 'styles/images/profile.jpg' %}" alt="profile photo" id="avatar">
            <h2 id="name1">{{user.name}}</h2>
            <h3 id="loc">{{user.location}}</h3>
        </div>
        <div id="details-card">
            <div id="a">
                <table>
                <tr>
                    <td><strong>Name :</strong></td>
                    <td>{{user.name}}</td>
                </tr>
                <tr>
                    <td><strong>Mail ID : </strong></td>
                    <td>{{user.email}}</td>
                </tr>
                <tr>
                    <td><strong>Profession :</strong></td>
                    <td>{{user.profession}}</td>
                </tr>
                <tr>
                    <td><strong>Contact :</strong></td>
                    <td>{{user.mobile}}</td>
                </tr>
                <tr>
                    <td><strong>Location :</strong></td>
                    <td>{{user.location}}</td>
                </tr>
                </table>
            </div>
        </div>
    </div>
    <div id="button-container">
        <button><a href="{% url 'signup' %}" class="buttons">Become an Investor</a></button>
        <button><a href="{% url 'verification1' %}" class="buttons">Register as a Startup</a></button>
   </div>
</body>
</html>
{% endblock content %}

sharkpitch/templates/base.html
{% include "header.html" %}

{% block content %}


{% endblock %}

sharkpitch/templates/investor_description_page.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Investor Description</title>
    <link rel="stylesheet" href="{% static 'css/investor_description_page.css' %}">
    <script src="https://unpkg.com/@cometchat-pro/chat@latest/CometChat.js"></script>
    <style>
        #openChat {
            background-color: #007bff;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
          }
        
          #openChat:hover {
            background-color: #0056b3;
          }
    </style>
</head>

  <!-- Header Section -->
<header>
    <div class="logo-container">
        <img src="{% static 'images/shark_pitch_logo.jpg' %}" alt="" id="logo">
        <a href="{% url 'home' %}" id="shark">SHARK PITCH</a>
    </div>
    <nav>
        <a href="{% url 'home' %}" id="about">About Us</a>
        <a href="{% url 'home' %}" id="contact">Contact Us</a>
        <a href="{% url 'accounts:logout' %}" id="logout">Logout</a>
        <img src="{% static 'images/profile.jpg' %}" alt="" id="prof">
    </nav>
</header>
<body>

    <!-- Investor Profile Section -->
    <div class="profile-container">
        <div class="profile-card">
            <!-- Left Box with Profile Info -->
            <div class="profile-info-box">
                <div class="profile-info">
                    <img src="{% static 'images/profile.jpg' %}" alt="Profile Avatar" class="avatar">
                    <h2>R. Raghuram</h2>
                    <p class="title">Full-Time Investor</p>
                    <p>Hyd, India</p>
                </div>
            </div>

            <!-- Right Box with Profile Details -->
            <div class="profile-details-box">
                <div class="profile-details">
                    <table>
                        <tr>
                            <td><strong>Name</strong></td>
                            <td>R. Raghuram</td>
                        </tr>
                        <tr>
                            <td><strong>Profession</strong></td>
                            <td>Founder Chairman of Stark Industries, Investor</td>
                        </tr>
                        <tr>
                            <td><strong>E-mail</strong></td>
                            <td>rraghuram@starkindustries.com</td>
                        </tr>
                        <tr>
                            <td><strong>Contact no.</strong></td>
                            <td>9876543210</td>
                        </tr>
                        <tr>
                            <td><strong>Location</strong></td>
                            <td>Hyd, India</td>
                        </tr>
                        <tr>
                            <td><strong>Previous Investments</strong></td>
                            <td>Boat, Cred, Skyroot Aerospace</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        
        <!-- Buttons -->
        <div class="button-container">
            <button  id="cometchat-btn" onclick="openCometChatPopup()">Communicate with Investor</button>
            
            <button>Real-time Video Conference</button>
        </div>
    </div>
    
</body>
<script>
    const appID = "267727497461a0e1";
    const region = "IN";
    const authKey = "0ac2aea0a9c16bcded63bb07ab7428dfeb3ca661"; // Needed for logging in users
    
    // Initialize CometChat
    CometChat.init(appID, new CometChat.AppSettingsBuilder().subscribePresenceForAllUsers().setRegion(region).build())
      .then(() => {
        console.log("CometChat initialized successfully");
      })
      .catch(error => {
        console.error("CometChat initialization failed:", error);
      });
  
  
    // Open CometChat widget or window
    function openCometChatPopup() {
        // Example: login the user first if not already logged in
        const userUID = "USER_UID";  // Replace with the actual user ID
    
        CometChat.login(userUID, authKey)
          .then(user => {
            console.log("User logged in successfully:", user);
            
            // Launch the CometChat pop-up widget
            CometChatWidget.launch({
              widgetID: "f9bd6f3b-2455-42c8-878a-238c4c1e1246",  // Replace with your CometChat widget ID
              docked: false,               // Pop-up window mode
              alignment: "right",          // "left" or "right"
              roundedCorners: true,        // Rounded corners for the pop-up window
              height: "500px",             // Height of the pop-up window
              width: "400px",              // Width of the pop-up window
            });
          })
          .catch(error => {
            console.error("Error logging in:", error);
          });
      }
  </script>
</html>
{% endblock %}

sharkpitch/templates/sign_up_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
    <link rel="stylesheet" href="{% static 'css/sign_up.css' %}">
</head>
<body>
    <!-- Header Section -->
    <header>
        <div class="logo-container">
            <img src="{% static 'images/shark_pitch_logo.jpg' %}" alt="Shark Pitch Logo" id="logo">
            <a href="{% url 'home' %}" id="shark">SHARK PITCH</a>
        </div>
        <nav>
            <a href="{% url 'home' %}" id="about">About Us</a>
            <a href="{% url 'home' %}" id="contact">Contact Us</a>
            <a href="{% url 'login' %}" id="register">Login</a>
        </nav>
    </header>

    <!-- Sign Up Section -->
    <div class="signup-container">
        <!-- Left Column with Form -->
        <div class="signup-form">
           
            <h2>Sign up</h2>
            <p>Already have an account? <a href="{% url 'login' %}">Login here</a></p>
            <form method="post" id="signup-form" action="{% url 'accounts:signup_view' %}">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group">
                        <label for="name"><strong>Name:</strong></label>
                        <input type="text" id="name" name="name" required>
                    </div>
                    <div class="form-group">
                        <label for="mobile"><strong>Mobile:</strong></label>
                        <input type="tel" id="mobile" name="mobile" required>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label for="password"><strong>Password:</strong></label>
                        <input type="password" id="password" name="password" required>
                    </div>
                    <div class="form-group">
                        <label for="profession"><strong>Profession:</strong></label>
                        <input type="text" id="profession" name="profession" required>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label for="email"><strong>Email ID:</strong></label>
                        <input type="email" id="email" name="email" required>
                    </div>
                    
                    <div class="form-group">
                        <label for="location"><strong>Location:</strong></label>
                        <input type="text" id="location" name="location" placeholder="City , Country" required>
                    </div>
                </div>
                <input type="hidden" id="role" name="role" value="Investor">
                <p><strong>Sign up as:</strong></p>
                <button type="submit" class="role-button" name="user_type" value="investor" onclick="setRole('Investor'); window.location.href='{% url 'login' %}'">Investor</button>
                <button type="submit" class="role-button"  name="user_type" value="startup" onclick="setRole('Entrepreneur'); window.location.href='{% url 'accounts:startup_register1_view' %}'">Entrepreneur</button>
                <button type="submit" class="role-button"  name="user_type" value="user" onclick="setRole('User'); window.location.href='{% url 'accounts:Investor_landing' %}'">User</button>
            </form>
        </div>
        
        <!-- Right Column with Image -->
        <div class="signup-image">
            <img src="{% static 'images\sign_up.jpg' %}" alt="Signup Illustration">
        </div>
    </div>
    <script>
        function setRole(role) {
            document.getElementById('role').value = role;
        }
    </script>
</body>
</html>

sharkpitch/templates/startup_verification_page4.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Team and Experience</title>
    <link rel="stylesheet" href="{% static 'css/startup_verification_pages/page2.css' %}">
</head>
<body>
    <!-- Header Section -->
    <header>
        <div class="logo-container">
            <img src="{% static 'images/shark_pitch_logo.jpg' %}" alt="Shark Pitch Logo" id="logo">
            <a href="{% url 'home' %}" id="shark">SHARK PITCH</a>
        </div>
        <nav>
            <a href="{% url 'home' %}" id="about">About Us</a>
            <a href="{% url 'home' %}" id="contact">Contact Us</a>
            <a href="{% url 'login' %}" id="logout">Login</a>
            <img src="{% static 'images/profile.jpg' %}" alt="Profile" id="prof">
        </nav>
    </header>

    <!-- Financials and Business Model Section -->
    <div class="questions-container">
        <h2>Team and Experience</h2>

        <!-- Questions -->
        <form id="questionsForm" method="post" action="{% url 'accounts:startup_register4_view' %}">
            {% csrf_token %}
            <div class="questions">
                <div class="question">
                    <p>1. What is your background and experience?</p>
                    <input type="text" name="q1" id="backgroundExperience" placeholder="Investors want to know about the founders' and key team members' relevant experience and skills.">
                </div>
                <div class="question">
                    <p>2. What is the composition of your team?</p>
                    <input type="text" name="q2" id="teamComposition" placeholder="Investors want to know about the team structure, roles, and responsibilities.">
                </div>
                
                <button type="submit" >Next</button>
            </div>
        </form>
    </div>

</body>
</html>

sharkpitch/templates/startup_verification_page7.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Timing and Terms</title>
    <link rel="stylesheet" href="{% static 'css/startup_verification_pages/page2.css' %}">
</head>
<body>
    <!-- Header Section -->
    <header>
        <div class="logo-container">
            <img src="{% static 'images/shark_pitch_logo.jpg' %}" alt="Shark Pitch Logo" id="logo">
            <a href="{% url 'home' %}" id="shark">SHARK PITCH</a>
        </div>
        <nav>
            <a href="{% url 'home' %}" id="about">About Us</a>
            <a href="{% url 'home' %}" id="contact">Contact Us</a>
            <a href="{% url 'login' %}" id="logout">Login</a>
            <img src="{% static 'images/profile.jpg' %}" alt="Profile" id="prof">
        </nav>
    </header>

    <!-- Timing and Terms Section -->
    <div class="questions-container">
        <h2>Timing and Terms</h2>

        <!-- Questions -->
        <form id="questionsForm" method="post" action="{% url 'accounts:startup_register7_view' %}">
            {% csrf_token %}
            <div class="questions">
                <div class="question">
                    <p>1. How much are you looking to raise and what are the terms?</p>
                    <input type="text" name="q1" id="fundingAmountTerms" placeholder="Investors want to know the funding requirements and the terms of the investment.">
                </div>
                <div class="question">
                    <p>2. What are the potential risks to the business?</p>
                    <input type="text" name="q2" id="businessRisks" placeholder="Describe any potential risks to the business.">
                </div>
                
                <button type="submit" >Next</button>
            </div>
        </form>
    </div>

</body>
</html>

sharkpitch/templates/startup_verification_page8.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Miscellaneous</title>
    <link rel="stylesheet" href="{% static 'css/startup_verification_pages/page2.css' %}">
</head>
<body>
    <!-- Header Section -->
    <header>
        <div class="logo-container">
            <img src="{% static 'images/shark_pitch_logo.jpg' %}" alt="Shark Pitch Logo" id="logo">
            <a href="{% url 'home' %}" id="shark">SHARK PITCH</a>
        </div>
        <nav>
            <a href="{% url 'home' %}" id="about">About Us</a>
            <a href="{% url 'home' %}" id="contact">Contact Us</a>
            <a href="{% url 'login' %}" id="logout">Login</a>
            <img src="{% static 'images/profile.jpg' %}" alt="Profile" id="prof">
        </nav>
    </header>

    <!-- Financials and Business Model Section -->
    <div class="questions-container">
        <h2>Miscellaneous</h2>

        <!-- Questions -->
        <form id="questionsForm" method="post" action="{% url 'accounts:startup_register8_view' %}">
            {% csrf_token %}
            <div class="questions">
                <div class="question">
                    <p>1. How did you come up with this idea?</p>
                    <input type="text" name="q1" id="problemSolved" placeholder="Investors want to know about the startup's origin and the founders' vision.">
                </div>
                <div class="question">
                    <p>2. What are your plans for scaling the business?</p>
                    <input type="text" name="q2" id="pointOfDifference" placeholder="Investors want to know about the startup's growth strategy and how it will achieve scalability.">
                </div>
                <div class="question">
                    <p>3. What are your key competitors and how do you differentiate yourself?</p>
                    <input type="text" name="q3" id="totalAddressableMarket" placeholder="Investors want to know about the competitive landscape and how the startup stands out.">
                </div>
                
                <button type="submit" >Next</button>
            </div>
        </form>
    </div>

</body>
</html>